const posts = [
  {
    id: 1,
    title: "Way For A Green Future",
    text: "Sustainability is no longer an optional endeavor for businesses.",
    author: "Marcus King",
    authorAvatar: require("@/assets/common/authors/author-4.jpg"),
    image: require("@/assets/posts/Sustain.jpg"),
    monthPost: "September",
    dayPost: "09",
    timeRead: "1",
    badge: "Sustainability",
  },
  {
    id: 2,
    title: "World Of Bioluminescence",
    text: "Sustainability is no longer an optional endeavor for businesses.",
    author: "Emily Davis",
    authorAvatar: require("@/assets/common/authors/author-2.jpg"),
    image: require("@/assets/posts/Nature.jpg"),
    monthPost: "October",
    dayPost: "03",
    timeRead: "8",
    badge: "Nature",
  },
  {
    id: 3,
    title: "The Power Of Networking",
    text: "Sustainability is no longer an optional endeavor for businesses.",
    author: "Ayana Carter",
    authorAvatar: require("@/assets/common/authors/author-3.jpg"),
    image: require("@/assets/posts/Networking.jpg"),
    monthPost: "October",
    dayPost: "03",
    timeRead: "2",
    badge: "Business",
  },
  {
    id: 4,
    title: "A Journey Through Time",
    text: "Sustainability is no longer an optional endeavor for businesses.",
    author: "Jason Williams",
    authorAvatar: require("@/assets/common/authors/author-1.jpg"),
    image: require("@/assets/posts/Music.jpg"),
    monthPost: "September",
    dayPost: "09",
    timeRead: "7",
    badge: "Music",
  },
  {
    id: 5,
    title: "A Transformative Journey",
    text: "One of the most evident trends in the future of VR is the continued improvement of hardware.",
    author: "Jason Williams",
    authorAvatar: require("@/assets/common/authors/author-1.jpg"),
    image: require("@/assets/posts/Tech.jpg"),
    monthPost: "August",
    dayPost: "21",
    timeRead: "34",
    badge: "Technology",
  },
  {
    id: 6,
    title: "The Cultural Fusion",
    text: "Cross-cultural exchange refers to the sharing of ideas, customs, and practices between different cultures.",
    author: "Ayana Carter",
    authorAvatar: require("@/assets/common/authors/author-3.jpg"),
    image: require("@/assets/posts/Culture.jpg"),
    monthPost: "September",
    dayPost: "3",
    timeRead: "12",
    badge: "Culture",
  },
  {
    id: 7,
    title: "Mastering Productivity",
    text: "Productivity is the cornerstone of personal and professional success.",
    author: "Marcus King",
    authorAvatar: require("@/assets/common/authors/author-4.jpg"),
    image: require("@/assets/posts/Business.jpg"),
    monthPost: "September",
    dayPost: "3",
    timeRead: "22",
    badge: "Business",
  },
  {
    id: 8,
    title: "Fragile Balance Of Nature",
    text: "Nature, with its breathtaking landscapes, ecosystems, and web of life.",
    author: "Ayana Carter",
    authorAvatar: require("@/assets/common/authors/author-3.jpg"),
    image: require("@/assets/posts/Nature2.jpg"),
    monthPost: "August",
    dayPost: "21",
    timeRead: "22",
    badge: "Nature",
  },
  {
    id: 9,
    title: "The Power Of Music",
    text: "Music is a universal language that transcends, cultures, and generations.",
    author: "Ayana Carter",
    authorAvatar: require("@/assets/common/authors/author-1.jpg"),
    image: require("@/assets/posts/Music2.jpg"),
    monthPost: "September",
    dayPost: "3",
    timeRead: "5",
    badge: "Music",
  },
  {
    id: 10,
    title: "The Digital Age",
    text: "In an era characterized by rapid globalization and technological advancement.",
    author: "Emily Davis",
    authorAvatar: require("@/assets/common/authors/author-2.jpg"),
    image: require("@/assets/posts/Culture2.jpg"),
    monthPost: "September",
    dayPost: "3",
    timeRead: "19",
    badge: "Culture",
  },
  {
    id: 11,
    title: "The 5G Technology",
    text: "The world of technology is continually evolving, and the rollout of 5G.",
    author: "Marcus King",
    authorAvatar: require("@/assets/common/authors/author-4.jpg"),
    image: require("@/assets/posts/Tech2.jpg"),
    monthPost: "August",
    dayPost: "21",
    timeRead: "9",
    badge: "Technology",
  },
  {
    id: 12,
    title: "A Sustainable Living",
    text: "Sustainability is not just a buzzword; it's a way of life that holds the key to our planet's future.",
    author: "Emily Davis",
    authorAvatar: require("@/assets/common/authors/author-2.jpg"),
    image: require("@/assets/posts/Nature3.jpg"),
    monthPost: "September",
    dayPost: "3",
    timeRead: "5",
    badge: "Sustainability",
  }
];

export default posts;
